import pandas as pd 
import numpy as np
import pyspark as ps
from pyspark.sql.types import *
from pyspark.sql.functions import *
import builtins
import detect_delimeter
def detect_header(lines, delimiter):
    """
    Detects header row in messy raw data.
    """

    # -----------------------------
    # 1. Normalize
    # -----------------------------
    cleaned = [l.strip() for l in lines if l and l.strip()]

    if not cleaned:
        return {
            "status": "FAILED",
            "result": {"header_row_index": None},
            "metadata": {"confidence": 0.0}
        }

    # -----------------------------
    # 2. Score each row
    # -----------------------------
    scores = []

    for i, line in enumerate(cleaned):
        parts = line.split(delimiter)

        # feature 1: number of columns
        col_count = len(parts)

        # feature 2: text vs numeric ratio
        alpha_ratio = sum(p.replace("_", "").isalpha() for p in parts) / max(col_count, 1)

        # feature 3: similarity with next row (structure check)
        if i + 1 < len(cleaned):
            next_parts = cleaned[i + 1].split(delimiter)
            structure_match = 1 if len(next_parts) == col_count else 0
        else:
            structure_match = 0

        # final score (weighted heuristic)
        score = (alpha_ratio * 0.6) + (structure_match * 0.4)

        scores.append(score)

    # -----------------------------
    # 3. Pick best candidate
    # -----------------------------
    best_index = builtins.max(range(len(scores)), key=lambda i: scores[i])
    best_score = scores[best_index]

    # -----------------------------
    # 4. Extract header columns
    # -----------------------------
    header_columns = cleaned[best_index].split(delimiter)

    # -----------------------------
    # 5. Return structured output
    # -----------------------------
    return {
        "status": "SUCCESS",
        "result": {
            "header_row_index": best_index,
            "header_columns": header_columns
        },
        "metadata": {
            "confidence": round(best_score, 4),
            "rows_scored": len(scores)
        }
    }
delimiter = detect_delimiter(lines)

lines = [
    "Generated by HR System",
    "Export Date: 2026-06-20",
    "Department: Data Analytics",
    "",
    "profile_id;name;experience",
    "1;John Doe;Built ETL pipelines with Spark and Airflow",
    "2;Alice Smith;Worked on SQL dashboards and Power BI",
    "3;Bob Lee;Developed ML models using Python and Pandas",
    "4;Sara Khan;Built data lake pipelines in Databricks"
]

detect_header(lines, delimiter["result"]["delimiter"]) 